### ISSUE TITLE
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException

### ISSUE THREAD

**Issue by EdisonLinXxx** [microsoft/java-debug#295]
![image](https://user-images.githubusercontent.com/42260799/64006881-c0d6df00-cb45-11e9-9442-c407a2a2c863.png)
it maybe a bug,please fix quickly and i use 0.20.0 is ok!!!

**Comment by testforstephen** [comment]
We have addressed some update to mitigate this issue, could you verify whether to reproduce it in the latest 0.22.0 version? Thanks.

**Comment by sayederfanarefin** [comment]
Same problem here on windows. It tries to copy a file named "cp_6xyj72ckmfd8oe8gpliu2etse.jar" from temp. The file is not there and I think it is failing because of that. Need a solution. 
![vscodeerror1](https://user-images.githubusercontent.com/7608931/68082449-80fcd400-fde2-11e9-955f-5d52d174108b.PNG)
![Uploading vscodeerror2.PNG…]()

**Comment by sayederfanarefin** [comment]
Same problem here on windows. It tries to copy a file named "cp_6xyj72ckmfd8oe8gpliu2etse.jar" from temp. The file is not there and I think it is failing because of that. Need a solution. 
![vscodeerror1](https://user-images.githubusercontent.com/7608931/68082449-80fcd400-fde2-11e9-955f-5d52d174108b.PNG)
![vscodeerror2](https://user-images.githubusercontent.com/7608931/68082451-84905b00-fde2-11e9-8185-e17b27a16316.PNG)

**Comment by testforstephen** [comment]
Your user name contains white space, it duplicates with https://github.com/microsoft/vscode-java-debug/issues/678

**Comment by sayederfanarefin** [comment]
@testforstephen Thanks man. I changed to powershell and problem solved!

**Comment by dharantejv** [comment]
![image](https://user-images.githubusercontent.com/72353996/115366613-1b252780-a1e3-11eb-975e-195a5cb5b2ef.png)
iam getting this error from last 3days .how can i solve this?

**Comment by xin911** [comment]
last month, debug is all good. But now I am getting the same error. 
What happend..? Vscode is automatically updated? 
[Error - 9:38:12 AM] 2022年12月29日 上午9:38:12 [error response][launch]: Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
com.microsoft.java.debug.core.DebugException: Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
	at com.microsoft.java.debug.core.adapter.handler.LaunchWithDebuggingDelegate.lambda$launchInTerminal$0(LaunchWithDebuggingDelegate.java:147)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
![image](https://user-images.githubusercontent.com/11419372/209894715-83b5298d-0f52-49ce-a9b6-de636b987568.png)

**Comment by ANDERSONSX** [comment]
failed to launch debuggee in terminal. reason com.sun.jdi.connect.transporttimeoutexception

**Comment by ANDERSONSX** [comment]
Ajuda por favor
