### ISSUE TITLE
setBreakpoints request before launch fails with "Empty debug session"

### ISSUE THREAD

**Issue by dradtke** [microsoft/java-debug#316]
According to the diagram shown [here](https://microsoft.github.io/debug-adapter-protocol/overview), the order of requests the client should make looks like this:

1. `initialize`
2. Any number of `setBreakpoints` or similar calls
3. `launch`

I'm experimenting with building a Debug Adapter Protocol plugin for vim, and so far I've been able to successfully begin the debug server via the `vscode.java.startDebugSession` command and send it an `initialize` request. The initialization succeeds, and then when I try to execute `setBreakpoints` I get an error with the message "Empty debug session."

From looking at the source for [DebugAdapterContext.java](https://github.com/microsoft/java-debug/blob/master/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java), it looks like the debug session isn't set until a call to either `launch` or `attach`, but that goes counter to the above series of requests.

What is the correct order here? Is the diagram wrong, or am I missing something here?

**Comment by dradtke** [comment]
Any updates on this?

**Comment by akaroml** [comment]
> Any updates on this?

Thanks for reaching out @dradtke. We'll be able to provide an answer next week.

**Comment by testforstephen** [comment]
The diagram you shared is just a sample sequence for gdb, it isn't applied to the java implementation.

The key point to determine when to deal with setBreakpoints request is `InitializedEvent`, see the [DAP protocol](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized). This event indicates that the debugger is ready to accept configuration requests (e.g. SetBreakpointsRequest, SetExceptionBreakpointsRequest).

In the java-debug implementation, you must handle setBreakpoints request after launch request, because the `InitializedEvent` is sent in the launch request handler, see the [code](https://github.com/microsoft/java-debug/blob/master/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithDebuggingDelegate.java#L214).
